(
 ("default" . ((user-emacs-directory . "~/.config/jose-emacs")
            (server-name . "jose")
            )
  )
 ("jose" . ((user-emacs-directory . "~/.config/jose-emacs")
            (server-name . "jose")
            )
  )
 ("doom" . ((user-emacs-directory . "~/.config/emacs")
            (server-name . "doom")
            (env . (("DOOMDIR" . "~/.config/doom")))
            )
  )
 ("spacemacs" . ((user-emacs-directory . "~/.config/spacemacs")
                 (server-name . "spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.spacemacs.d")))
                 )
  )
 ("prelude" . ((user-emacs-directory . "~/.config/prelude")
               (server-name . "prelude")
               )
  )
 )
